# Пример 1
### Транспонирование матрицы

In [1]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [2]:
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [4]:
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 8  4]
 [10 12]
 [12 11]]


In [5]:
print(R)

[[ 8  4]
 [10 12]
 [12 11]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [7]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[19 43]
 [22 50]]


In [8]:
print(R)

[[19 43]
 [22 50]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [9]:
A = np.matrix(' 1 2 3; 4 5 6')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [10]:
print(R)

[[ 3 12]
 [ 6 15]
 [ 9 18]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [11]:
A = np.matrix('1 2; 3 4')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

-2


In [12]:
print(format(A_T_det, '.9g'))

-2
