# Пример 2
### Умножение матрицы на число

In [1]:
import numpy as np

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [2]:
A = np.matrix('1 2; 3 4')
L = 1 * A
R = A
print(L)

[[1 2]
 [3 4]]


In [3]:
print(R)

[[1 2]
 [3 4]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [4]:
A = np.matrix('1 2; 3 4')
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0]
 [0 0]]


In [5]:
print(R)

[[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [7]:
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[ 5 10]
 [15 20]]


In [8]:
print(R)

[[ 5 10]
 [15 20]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [9]:
L = (p * q) * A
R = p * (q * A)
print(L)

[[ 6 12]
 [18 24]]


In [10]:
print(R)

[[ 6 12]
 [18 24]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [12]:
B = np.matrix('5 6; 7 8')
k = 3
L = k * (A + B)
R = k * A + k * B
print(L)

[[18 24]
 [30 36]]


In [13]:
print(R)

[[18 24]
 [30 36]]
