# Пример 3
### Сложение матриц

In [1]:
import numpy as np

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [2]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
L = A + B
R = B + A
print(L)

[[ 6  8]
 [10 12]]


In [3]:
print(R)

[[ 6  8]
 [10 12]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [4]:
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)

[[ 7 15]
 [19 15]]


In [5]:
print(R)

[[ 7 15]
 [19 15]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей :

In [6]:
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)

[[0 0]
 [0 0]]


In [7]:
print(Z)

[[0 0]
 [0 0]]
