# Пример 4
### Умножение матриц

In [1]:
import numpy as np

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [2]:
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[192 252]
 [436 572]]


In [3]:
print(R)

[[192 252]
 [436 572]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [4]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[35 42]
 [77 94]]


In [5]:
print(R)

[[35 42]
 [77 94]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [6]:
L = A.dot(B)
R = B.dot(A)
print(L)

[[19 22]
 [43 50]]


In [7]:
print(R)

[[23 34]
 [31 46]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [8]:
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)

[[1 2]
 [3 4]]


In [9]:
print(R)

[[1 2]
 [3 4]]


In [10]:
print(A)

[[1 2]
 [3 4]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [ ]:
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)