# Пример 5
### Определитель матрицы

In [1]:
import numpy as np

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [2]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [3]:
print(A.T)

[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]


In [4]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)

-14.0


In [5]:
print(det_A_t)

-14.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [6]:
A = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(A)

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]


In [7]:
np.linalg.det(A)

0.0

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [8]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [9]:
B = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(B)

[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]


In [10]:
round(np.linalg.det(A), 3)

-14.0

In [11]:
round(np.linalg.det(B), 3)

14.0

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [12]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [13]:
np.linalg.det(A)

0.0

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [14]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [15]:
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]


In [16]:
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k

-28.0

In [17]:
det_B

-28.0

Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [18]:
A = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
B = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]


In [19]:
print(A)

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]


In [20]:
print(B)

[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]


In [21]:
round(np.linalg.det(C), 3)

4.0

In [22]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

4.0

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [23]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [24]:
print(B)

[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]


In [25]:
round(np.linalg.det(A), 3)

-14.0

In [26]:
round(np.linalg.det(B), 3)

-14.0

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [27]:
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [28]:
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
A[1, :] = k * A[0, :]
print(A)

[[-4 -1  2]
 [-8 -2  4]
 [ 8  3  1]]


In [ ]:
round(np.l)