# Пример 6
### Обратная матрица

In [1]:
import numpy as np

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [2]:
A = np.matrix('1. -3.; 2. 5.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[ 1. -3.]
 [ 2.  5.]]


In [3]:
print(A_inv_inv)

[[ 1. -3.]
 [ 2.  5.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [4]:
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


In [5]:
print(R)

[[ 0.45454545 -0.18181818]
 [ 0.27272727  0.09090909]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [6]:
B = np.matrix('7. 6.; 1. 8.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]


In [7]:
print(R)

[[ 0.09454545  0.03272727]
 [-0.03454545  0.00727273]]
