# Индивидуальное задание 1

In [1]:
import numpy as np

Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [3]:
A = np.matrix('1 2 3; 7 8 9')
print(A)

[[1 2 3]
 [7 8 9]]


In [4]:
R = (A.T).T
print(R)

[[1 2 3]
 [7 8 9]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [5]:
B = np.matrix('2 5 8; 9 12 10')
L = (A + B).T
R = A.T + B.T
print(L)

[[ 3 16]
 [ 7 20]
 [11 19]]


In [6]:
print(R)

[[ 3 16]
 [ 7 20]
 [11 19]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных матриц расставленных в обратном порядке:

In [7]:
A = np.matrix('1 9; 11 12')
B = np.matrix('0 4; 3 2')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)

[[27 36]
 [22 68]]


In [8]:
print(R)

[[27 36]
 [22 68]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого числа на транспонированную матрицу:

In [9]:
A = np.matrix('11 5 3; 23 4 9')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[33 69]
 [15 12]
 [ 9 27]]


In [10]:
A = np.matrix(' 5 7 13; 23 4 9')
k = 3
L = (k * A).T
R = k * (A.T)
print(L)

[[15 69]
 [21 12]
 [39 27]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [11]:
A = np.matrix('5 7; 3 1')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))

-16


In [12]:
print(format(A_T_det, '.9g'))

-16


## Умножение матрицы на число

Свойство 1. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [13]:
A = np.matrix('5 7 3; 3 1 9')
L = 1 * A
R = A
print(L)

[[5 7 3]
 [3 1 9]]


In [14]:
print(R)

[[5 7 3]
 [3 1 9]]


Свойство 2. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой равна исходной матрицы:

In [16]:
Z = np.matrix('0 0; 0 0')
L = 0 * A
R = Z
print(L)

[[0 0 0]
 [0 0 0]]


In [17]:
print(R)

[[0 0]
 [0 0]]


Свойство 3. Произведение матрицы на сумму чисел равно сумме произведений матрицы на каждое из этих чисел:

In [18]:
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)

[[25 35 15]
 [15  5 45]]


In [19]:
print(R)

[[25 35 15]
 [15  5 45]]


Свойство 4. Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [20]:
L = (p * q) * A
R = p * (q * A)
print(L)

[[30 42 18]
 [18  6 54]]


In [21]:
print(R)

[[30 42 18]
 [18  6 54]]


Свойство 5. Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [26]:
A = np.matrix('7 2 4; 6 3 2; 9 5 7')
B = np.matrix('1 2 3; 2 3 2; 2 3 3')
v = 3
L = v * (A + B)
R = v * A + B * v
print(L)

[[24 12 21]
 [24 18 12]
 [33 24 30]]


In [27]:
print(L)

[[24 12 21]
 [24 18 12]
 [33 24 30]]


## Сложение матриц

Свойство 1. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [31]:
A = np.matrix('3 9; 4 10')
B = np.matrix('1 2; 5 6')
L = A + B
R = B + A
print(L)

[[ 4 11]
 [ 9 16]]


In [32]:
print(R)

[[ 4 11]
 [ 9 16]]


Свойство 2. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от порядка, в котором эта операция будет выполняться:

In [34]:
C = np.matrix('11 3; 2 14')
L = A + (B + C)
R = (A + B) + C
print(L)

[[15 14]
 [11 30]]


In [35]:
print(R)

[[15 14]
 [11 30]]


Свойство 3. Для любой матрицы существует противоположная ей , такая, что их сумма является нулевой матрицей :

In [40]:
Z = np.matrix('0 0; 0 0')
L = A + (-1)*A
print(L)

[[0 0]
 [0 0]]


In [37]:
print(Z)

[[0 0]
 [0 0]]


## Умножение матриц

Свойство 1. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [38]:
A = np.matrix('1 2; 3 4')
B = np.matrix('7 5; 2 6')
C = np.matrix('9 8; 5 7')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)

[[184 207]
 [456 505]]


In [39]:
print(R)

[[184 207]
 [456 505]]


Свойство 2. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:

In [41]:
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)

[[30 39]
 [76 91]]


In [42]:
print(R)

[[30 39]
 [76 91]]


Свойство 3. Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [44]:
L = A.dot(B)
R = B.dot(A)
print(L)

[[11 17]
 [29 39]]


In [45]:
print(R)

[[22 34]
 [20 28]]


Свойство 4. Произведение заданной матрицы на единичную равно исходной матрице:

In [46]:
E = np.matrix('1 0; 0 1')
L = E.dot(A)
R = A.dot(E)
print(L)

[[1 2]
 [3 4]]


In [47]:
print(R)

[[1 2]
 [3 4]]


Свойство 5. Произведение заданной матрицы на нулевую матрицу равно нулевой матрице:

In [48]:
Z = np.matrix('0 0; 0 0')
L = Z.dot(A)
R = A.dot(Z)
print(L)

[[0 0]
 [0 0]]


## Определитель матрицы

Свойство 1. Определитель матрицы остается неизменным при ее транспонировании:

In [50]:
A = np.matrix('-7 6 11; 2 0 -6; 4 7 2')
print(A)

[[-7  6 11]
 [ 2  0 -6]
 [ 4  7  2]]


In [51]:
print(A.T)

[[-7  2  4]
 [ 6  0  7]
 [11 -6  2]]


In [52]:
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)

-308.0


In [53]:
print(det_A_t)

-308.0


Свойство 2. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [55]:
A = np.matrix('-14 4 8; 0 0 0; 7 6 1')
print(A)

[[-14   4   8]
 [  0   0   0]
 [  7   6   1]]


In [56]:
np.linalg.det(A)

0.0

Свойство 3. При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [57]:
A = np.matrix('-10 2 13; 1 0 -4; 8 3 1')
print(A)

[[-10   2  13]
 [  1   0  -4]
 [  8   3   1]]


In [58]:
B = np.matrix('1 0 -4; -10 2 13; 8 3 1')
print(B)

[[  1   0  -4]
 [-10   2  13]
 [  8   3   1]]


In [59]:
round(np.linalg.det(A), 3)

-147.0

In [60]:
round(np.linalg.det(B), 3)

147.0

Свойство 4. Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [63]:
A = np.matrix('-16 24 6; -16 24 6; 12 4 5')
print(A)

[[-16  24   6]
 [-16  24   6]
 [ 12   4   5]]


In [64]:
np.linalg.det(A)

0.0

Свойство 5. Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [65]:
A = np.matrix('-16 24 6; -16 24 6; 12 4 5')
print(A)

[[-16  24   6]
 [-16  24   6]
 [ 12   4   5]]


In [66]:
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[-16  24   6]
 [-16  24   6]
 [ 24   8  10]]


In [67]:
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
det_A * k

0.0

In [68]:
det_B

0.0

Свойство 6. Если все элементы строки или столбца можно представить как сумму двух слагаемых, то определитель такой матрицы равен сумме определителей двух соответствующих матриц:

In [69]:
A = np.matrix('-10 2 13; 1 0 -4; 8 3 1')
B = np.matrix('-10 2 13; 8 3 2; 8 3 1')
C = A.copy()
C[1, :] += B[1, :]
print(C)

[[-10   2  13]
 [  9   3  -2]
 [  8   3   1]]


In [70]:
print(A)

[[-10   2  13]
 [  1   0  -4]
 [  8   3   1]]


In [71]:
print(B)

[[-10   2  13]
 [  8   3   2]
 [  8   3   1]]


In [72]:
round(np.linalg.det(C), 3)

-101.0

In [73]:
round(np.linalg.det(A), 3) + round(np.linalg.det(B), 3)

-101.0

Свойство 7. Если к элементам одной строки прибавить элементы другой строки, умноженные на одно и тоже число, то определитель матрицы не изменится:

In [74]:
A = np.matrix('-11 2 11; 3 0 -2; 9 1 6')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)


[[-11   2  11]
 [  3   0  -2]
 [  9   1   6]]


In [75]:
print(B)

[[-11   2  11]
 [-19   4  20]
 [  9   1   6]]


In [76]:
round(np.linalg.det(A), 3)

-61.0

In [77]:
round(np.linalg.det(B), 3)

-61.0

Свойство 8. Если строка или столбец матрицы является линейной комбинацией других строк (столбцов), то определитель такой матрицы равен нулю:

In [79]:
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

0.0

Свойство 9. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [81]:
A = np.matrix('-10 2 13; 1 0 -4; 8 3 1')
k = 2
A[1, :] = k * A[0, :]
print(A)

[[-10   2  13]
 [-20   4  26]
 [  8   3   1]]


In [82]:
round(np.linalg.det(A), 3)

0.0

## Обратная матрица

Свойство 1. Обратная матрица обратной матрицы есть исходная матрица:

In [83]:
A = np.matrix('11. -2.; -3. 15.')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)

[[11. -2.]
 [-3. 15.]]


In [84]:
print(A_inv_inv)

[[11. -2.]
 [-3. 15.]]


Свойство 2. Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [85]:
L = np.linalg.inv(A.T)
R = (np.linalg.inv(A)).T
print(L)

[[0.09433962 0.01886792]
 [0.01257862 0.06918239]]


In [86]:
print(R)

[[0.09433962 0.01886792]
 [0.01257862 0.06918239]]


Свойство 3. Обратная матрица произведения матриц равна произведению обратных матриц:

In [88]:
B = np.matrix('9. -1.; 13. 4.')
L = np.linalg.inv(A.dot(B))
R = np.linalg.inv(B).dot(np.linalg.inv(A))
print(L)

[[ 0.00808625  0.00243871]
 [-0.02156334  0.00936979]]


In [89]:
print(R)

[[ 0.00808625  0.00243871]
 [-0.02156334  0.00936979]]
