# Индивидуальное задание 2

### 1) Метод Крамера

In [5]:
import numpy as np

In [15]:
A = np.matrix('2 4 -3; 3 -1 2; 1 2 1')
print(A)

[[ 2  4 -3]
 [ 3 -1  2]
 [ 1  2  1]]


In [16]:
B = np.matrix('10; -5; 4')
print(B)

[[10]
 [-5]
 [ 4]]


In [17]:
detA = np.linalg.det(A)
print("|A| =", detA)

|A| = -35.00000000000001


In [18]:
if detA != 0:
    A_inv = np.linalg.inv(A)
    X = A_inv.dot(B)
    x = int(round(X[0, 0]))
    y = int(round(X[1, 0]))
    z = int(round(X[2, 0]))
    print("Решение:")
    print(f"x = {x}")
    print(f"y = {y}")
    print(f"z = {z}")

Решение:
x = -1
y = 2
z = 0


In [47]:
result = A.dot(X)
print("Проверка: {}*{} + {}*{} + {}*{} = {}".format(A[0,0], x, A[0,1], y, A[0,2], z, B[0,0]))
if np.allclose(result, B):
    print("Проверка пройдена")
else:
    print("Проверка не пройдена")

Проверка: 5*-1 + -1*2 + -1*0 = 0
Проверка не пройдена


### 2) Матричный метод

In [25]:
a1 = [5, 1, 4]
a2 = [-1, 2, 3]
a3 = [-1, 3, 2]
b = [0, 4, 16]

In [26]:
A = np.transpose(np.matrix([a1, a2, a3]))
print(A)

[[ 5 -1 -1]
 [ 1  2  3]
 [ 4  3  2]]


In [27]:
B = np.transpose(np.matrix([b]))
print(B)

[[ 0]
 [ 4]
 [16]]


In [28]:
A_det = round(np.linalg.det(A))
print(f"|A| = {A_det}")

|A| = -30


In [29]:
if A_det != 0:
    X = []
    for i in range(A.shape[1]):
        A_temp = A.copy()
        A_temp[:, i] = B
        X.append(round(np.linalg.det(A_temp) / A_det))

In [48]:
print("Решение:")
for i, var in enumerate(["x", "y", "z"]):
    print(f"{var} = {X[i]}")

Решение:
x = 1
y = 7
z = -3
